CREATE TABLE public.geoname (
	id numeric NULL,
	"name" varchar NULL,
	ascii varchar NULL,
	alt_name varchar NULL,
	lat numeric NULL,
	long numeric NULL,
	feat_class varchar NULL,
	feat_code varchar NULL,
	country varchar NULL,
	cc2 bool NULL,
	admin1 varchar NULL,
	admin2 numeric NULL,
	admin3 numeric NULL,
	admin4 bool NULL,
	population numeric NULL,
	elevation numeric NULL,
	dem numeric NULL,
	tz varchar NULL,
	modified_at date NULL
);
